export type TechnologySourceDefinition = {
  id: string;
  name: string;
  provider: string;
  sourceUrl: string;
  feedUrl: string;
  accessType: "rss" | "atom";
  professionalAreas: string[];
  priority: "P0" | "P1";
  active: boolean;
  zeroAdditionalCost: true;
  billingRequired: false;
};

export const technologySources: TechnologySourceDefinition[] = [
  {
    id: "SRC-005",
    name: "Microsoft Power Apps Blog",
    provider: "Microsoft",
    sourceUrl: "https://www.microsoft.com/en-us/power-platform/blog/power-apps/",
    feedUrl: "https://www.microsoft.com/en-us/power-platform/blog/power-apps/feed/",
    accessType: "rss",
    professionalAreas: [
      "power-apps",
      "power-platform",
      "canvas-apps",
      "model-driven-apps",
      "power-fx",
      "dataverse",
      "copilot",
      "alm",
      "governance",
      "low-code",
    ],
    priority: "P0",
    active: true,
    zeroAdditionalCost: true,
    billingRequired: false,
  },
  {
    id: "SRC-007",
    name: "Microsoft Power BI Blog",
    provider: "Microsoft",
    sourceUrl: "https://powerbi.microsoft.com/en-us/blog/",
    feedUrl: "https://powerbi.microsoft.com/en-us/blog/feed/",
    accessType: "rss",
    professionalAreas: [
      "power-bi",
      "dax",
      "semantic-model",
      "power-query",
      "analytics",
      "data-visualization",
      "power-bi-embedded",
      "fabric",
      "copilot",
      "ai",
    ],
    priority: "P0",
    active: true,
    zeroAdditionalCost: true,
    billingRequired: false,
  },
  {
    id: "SRC-008",
    name: "Microsoft 365 Blog",
    provider: "Microsoft",
    sourceUrl: "https://www.microsoft.com/en-us/microsoft-365/blog/",
    feedUrl: "https://www.microsoft.com/en-us/microsoft-365/blog/feed/",
    accessType: "rss",
    professionalAreas: [
      "ai-applied",
      "microsoft-365-copilot",
      "copilot-studio",
      "agents",
      "ai",
      "productivity",
      "sharepoint",
      "teams",
      "business-process",
    ],
    priority: "P0",
    active: true,
    zeroAdditionalCost: true,
    billingRequired: false,
  },
  {
    id: "SRC-004",
    name: "Microsoft Power Platform Blog",
    provider: "Microsoft",
    sourceUrl: "https://www.microsoft.com/en-us/power-platform/blog/",
    feedUrl: "https://www.microsoft.com/en-us/power-platform/blog/feed/",
    accessType: "rss",
    professionalAreas: [
      "power-platform",
      "power-apps",
      "power-automate",
      "dataverse",
      "copilot-studio",
      "power-pages",
      "governance",
      "alm",
      "connectors",
      "low-code",
      "ai-applied",
    ],
    priority: "P1",
    active: true,
    zeroAdditionalCost: true,
    billingRequired: false,
  },
  {
    id: "SRC-006",
    name: "Microsoft Power Automate Blog",
    provider: "Microsoft",
    sourceUrl: "https://www.microsoft.com/en-us/power-platform/blog/power-automate/",
    feedUrl: "https://www.microsoft.com/en-us/power-platform/blog/power-automate/feed/",
    accessType: "rss",
    professionalAreas: [
      "power-platform",
      "power-automate",
      "cloud-flows",
      "desktop-flows",
      "connectors",
      "approvals",
      "process-mining",
      "governance",
      "alm",
      "automation",
    ],
    priority: "P1",
    active: true,
    zeroAdditionalCost: true,
    billingRequired: false,
  },
  {
    id: "SRC-001",
    name: "GitHub Changelog",
    provider: "GitHub",
    sourceUrl: "https://github.blog/changelog/",
    feedUrl: "https://github.blog/changelog/feed/",
    accessType: "rss",
    professionalAreas: [
      "github",
      "git",
      "copilot",
      "actions",
      "projects",
      "software-development",
    ],
    priority: "P1",
    active: true,
    zeroAdditionalCost: true,
    billingRequired: false,
  },
  {
    id: "SRC-002",
    name: "Supabase Changelog",
    provider: "Supabase",
    sourceUrl: "https://supabase.com/changelog",
    feedUrl: "https://supabase.com/changelog-rss.xml",
    accessType: "rss",
    professionalAreas: [
      "supabase",
      "postgresql",
      "backend",
      "auth",
      "storage",
      "realtime",
    ],
    priority: "P1",
    active: true,
    zeroAdditionalCost: true,
    billingRequired: false,
  },
  {
    id: "SRC-003",
    name: "OpenAI Product Release Notes",
    provider: "OpenAI",
    sourceUrl: "https://openai.com/products/release-notes/",
    feedUrl: "https://openai.com/products/release-notes/rss.xml",
    accessType: "rss",
    professionalAreas: [
      "chatgpt",
      "codex",
      "ai",
      "agents",
      "software-development",
    ],
    priority: "P1",
    active: true,
    zeroAdditionalCost: true,
    billingRequired: false,
  },
];
